name: Hello World

on:
  push:
      branches:
        - main

jobs:
  hello_world_job:
      runs-on: ubuntu-24.04
      steps:
        - name: Say Hello World
          run: | 
            echo "Hello World"
